### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by hnhatr** [mac-s-g/react-json-view#121]
From the latest version, server-side rendering produces following issue

ReferenceError: window is not defined
    at C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:150552
    at C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:150507
    at e.exports (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:151009)
    at Object.<anonymous> (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:146201)
    at t (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:377)
    at Object.defineProperty.value (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:41330)
    at t (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:377)
    at Object.defineProperty.value (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:39991)
    at t (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:377)
    at t.exports (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:734)
    at C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:744
    at n (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:81)
    at Object.<anonymous> (C:\Users\hnhatr\Downloads\reactGo-master\node_modules\react-json-view\dist\main.js:1:253)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\hnhatr\Downloads\reactGo-master\compiled\webpack:\external "react-json-view":1:1)
    at __webpack_require__ (C:\Users\hnhatr\Downloads\reactGo-master\compiled\webpack:\webpack\bootstrap deda87cb735796675547:19:1)

help me please !!!

**Comment by mac-s-g** [comment]
i haven't tested ssr.  i'll take a look as soon as i get a chance.

**Comment by mac-s-g** [comment]
@hnhatr  i'm having trouble reproducing the error.

can you tell me more about what tools & config you're using for server-side rendering?

is there a github link that will give me some more info about your build?

**Comment by mac-s-g** [comment]
also, @hnhatr , it looks like you're not the only one running into "window is not defined" issues when using server-side rendering.

a [google search](https://www.google.com/search?q=%22server+side+rendering%22+%2B+%22window+is+not+defined%22&oq=%22server+side+rendering%22+%2B+%22window+is+not+defined%22&aqs=chrome..69i57.10725j0j1&sourceid=chrome&ie=UTF-8) shows quite a bit of people running into the same issue.

there should be tools to emulate the `window` global on the server.  [here is an example](https://github.com/reactjs/react-chartjs/issues/57) of someone solving the problem by faking a `window` variable.  I also believe there are plugins for ssr that initialize a global `window` object.

**Comment by Rid** [comment]
I'm having the same issue, none of the hacks seem to work as the plugin is loaded using webpack before the global can be set.

I believe the included lib with is causing the issue is:
https://github.com/zenorocha/clipboard.js/blob/a55c9ac513da6e6d01dfd6ceed9a930c596cf7e4/src/clipboard-action.js#L141

**Comment by indolent-developer** [comment]
This is due to style loader. module of webpack. https://github.com/webpack-contrib/style-loader/issues/272#issuecomment-345274784.

I guess we have to use different style loader if you want to support server side rendering. Do you support server side rendering ?

**Comment by Alchemist-V** [comment]
I am seeing this as well, any leads anyone?

**Comment by indolent-developer** [comment]
@Alchemist-V are you using server side rendering?  if yes can you disable it if not then you should use different style loader.
something similar to https://github.com/kriasoft/isomorphic-style-loader

**Comment by Rid** [comment]
@indolent-developer have you got this working with SSR? If so could you point me to a working fork/pull req?

**Comment by indolent-developer** [comment]
@Rid I was able to work this via disabling server side rendering of this component. No fork or pull.

**Comment by Alchemist-V** [comment]
@indolent-developer I got it working by trying to load the component lazily. Something like this:

`
var ReactJson = null;
/**
 * Component to initate loading of Context json 
 * for an asset.
 */
class JsonEditor extends React.Component{
	constructor() {
		super();
        }
       
       componentDidMount() {
		require.ensure(['react-json-view'], function() {
			try {
				ReactJson = require('react-json-view').default;
			} catch(err) {
				console.log('react-json-view:', err);
			}
		})
	}

        render () {
              return (
                      {  ReactJson == null ? "Unable to load content": 
                          <ReactJson src={context} onEdit={this.onEdit.bind(this)} />
                      }
              )
        }
`
Any concerns or feedback?

**Comment by indolent-developer** [comment]
@Alchemist-V looks fine to be. 

We do need a longterm solution for this though. A PR from some one. What does author have to say ? I am currently tied up :(

**Comment by Rid** [comment]
@Alchemist-V I can confirm it's working, thanks! I think a fork/pull req using isomorphic-style-loader is better but I don't have time to test right now

**Comment by mac-s-g** [comment]
I'm totally cool with swapping out the loaders if that fixes the issue.  anyone want to post a PR?  I'm happy to test, merge, and publish.

**Comment by indolent-developer** [comment]
i can try in few weeks currently tied up.

**Comment by Alchemist-V** [comment]
Thanks @Rid ! Let me see if i can file a PR for this. Hope the above hack works for all in the mean time.

**Comment by mansdahlstrom1** [comment]
Is there any updates on this ?

**Comment by charlieprynn** [comment]
I'm also interested in this.

**Comment by janouser11** [comment]
Same^

**Comment by janouser11** [comment]
Last week I had this working perfectly fine, after restarting project I only get a window is not defined error.  Any suggestions?

Thanks

**Comment by arjitkhullar** [comment]
resolved using : 
[NextJs Loading Components Dynamically](https://github.com/zeit/next.js/#3-with-no-ssr)

**Comment by xuchen81** [comment]
Same error.

**Comment by tomkiss** [comment]
Same error here.

**Comment by johnking** [comment]
I am using it with Gatsby, and get the same error.

**Comment by johnking** [comment]
one note: the hack code does not work for my case.

**Comment by johnking** [comment]
My workaround has two parts: 
1. use conditional rendering in your component like the code snippet below

```jsx
<div>
  { typeof window !== 'undefined' && ReactJsonViewt &&  <ReactJsonView  />}
</div>
```

2. Modify your webpack config to avoid loading the `react-json-view` during stage `build-html`, something like below:

```js
  // workaround for using react-json-view
  if (stage === 'build-html') {
    // console.log('inside build-html ...');
    actions.setWebpackConfig({
      module: {
        rules: [
          {
            test: /react-json-view/,
            use: loaders.null(),
          },
        ],
      },
    });
  }
```

**Comment by darrikonn** [comment]
Is this repo no longer maintained? (this is the most active thread, so I think it's worthwhile to ask this here)

**Comment by hoangdoan267** [comment]
For users using nextjs, you can use next/dynamic for this case
`const DynamicReactJson = dynamic(import('react-json-view'), {
  ssr: false
});`

return your json view with data like 
`<DynamicReactJson src={yourData}`

**Comment by MinosIE** [comment]
I solved this with the following code:

```
render() {
        let JsonDom;
        const { info } = this.state;
        if (!canUseWindow || !info) {
            JsonDom = <div />;
        } else {
            var ReactJson = require('react-json-view');
            JsonDom = <ReactJson.default src={info} />;
        }
        return (
            <div>
                <Button type="primary" block onClick={this.getDeviceInfo}>
                    getDeviceInfo
                </Button>
                <div>{JsonDom}</div>
            </div>
        );
    }
```
If you have a better way, please call me
Thanks

**Comment by nicolas-rodriguez-globant** [comment]
Same error.

**Comment by justinmchase** [comment]
The minified code at the point of the error is reported has the following code:
```js
(function(){return window&&document&&document.all&&!window.atob})
```

Its failing at that first reference to `window`, and is very near some other code related to base64 encoding data urls. This error appears shortly after ""The style-loader cannot be used in a non-browser environment".

I've confirmed its this line: https://github.com/mac-s-g/react-json-view/blob/master/webpack/webpack.config.js#L55

I've cloned and linked this repo locally and I can confirm that removing that loader from the webpack config allows the SSR to complete successfully (not sure if the component stops working or not though).

Here is a bug in that library that is related to this issue: https://github.com/webpack-contrib/style-loader/issues/272

Here is another bug which appears to fix this specific issue: https://github.com/webpack-contrib/style-loader/pull/250

There are multiple PR's in that repo that have been closed as won't fix for this issue because the project owner seems to think that this library wont' work in SSR environments anyway and so it shouldn't be fixed.

Here is the current code, which is different than the version we are using: https://github.com/webpack-contrib/style-loader/blob/de38c395cdf59f2babe54bf0e7e2f816baf36c74/src/runtime/injectStylesIntoStyleTag.js#L11

Updating `style-loader` to the latest version fixes this error but then it throws a new error later on saying `document is not defined` in a different spot...

I hate to say it but I think the real solution here is to redo `react-json-view`'s styling entirely to not be using sass or webpack to load and pack styles 😬 Or at the very worst, provide the css files separately and require the caller to figure out how they want to load the css files. Don't package the deployed code with built in css loading.

This is the line that probably needs to be removed ultimately: https://github.com/mac-s-g/react-json-view/blob/master/src/js/index.js#L13

And replace it with inline react styling:
https://reactjs.org/docs/dom-elements.html#style

Until that happens, I think you have to render your component dynamically with SSR off, in my case like this:

```ts
import React from 'react'
import dynamic from 'next/dynamic'

const App = dynamic({
  loader: import ('../components/app'),
  ssr: false
})
export default Index () {
  return (<App />)
}
```

**Comment by alexandre-lelain** [comment]
Here's a little workaround inspired by the previous answers, while SSR is still not supported:

```jsx
const theme = {...}

export default () => {
  if (typeof window !== "undefined") {
   const ReactJson = require('react-json-view').default
   return <ReactJson src={theme} />
  }
  return null
}
```

Tested on Gatsby v2. No extra webpack config needed.

**Comment by peter-reonomy** [comment]
This worked for me:
// Use this instead of `import` to prevent "window is not defined" error at build time
const ReactJson = typeof window !== 'undefined' ? require('react-json-view').default : null;

**Comment by samstr** [comment]
There's also this library: [https://www.npmjs.com/package/react-json-viewer](react-json-viewer).

Not quite as nice visually, but doesn't have the window issue

**Comment by denispasin** [comment]
@justinmchase I was afraid the SCSS would be gigantic but it's actually quite small. Did you try doing the refactor ?

**Comment by justinmchase** [comment]
No, but the issue persists for me, it would be nice to solve it but I assumed it was going to be a big refactor.

**Comment by denispasin** [comment]
I’ll look at it if I find the time.

**Comment by slorber** [comment]
Also had this problem, while I'm trying to integrate this lib in Docusaurus debug dashboard (WIP): 
https://github.com/facebook/docusaurus/pull/3229

My solution looks like:

```tsx
function BrowserOnly({
  children,
  fallback,
}: {
  children?: () => JSX.Element;
  fallback?: JSX.Element;
}): JSX.Element | null {
  if (!ExecutionEnvironment.canUseDOM || children == null) {
    return fallback || null;
  }

  return <>{children()}</>;
}

const BrowserOnlyReactJson = (props) => {
  return (
    <BrowserOnly>
      {() => {
        const ReactJson = require('react-json-view').default;
        return <ReactJson {...props} />;
      }}
    </BrowserOnly>
  );
};
```

**Comment by thomasjm** [comment]
I made a PR with the inline React styling solution at #298. If anyone would like to try it and confirm it works that would be helpful.

**Comment by panyamred** [comment]
> For users using nextjs, you can use next/dynamic for this case
> `const DynamicReactJson = dynamic(import('react-json-view'), { ssr: false });`
> 
> return your json view with data like
> `<DynamicReactJson src={yourData}`

import dynamic from "next/dynamic";

const DynamicReactJson = dynamic(import('react-json-view'), { ssr: false });

This solved the issue.

**Comment by arifszn** [comment]
Confirming this issue while production building in Docusaurus v2. Not recommending with Docusaurus.

**Comment by slorber** [comment]
@arifszn I'm the current lead maintainer of Docusaurus and you should just do something similar to what I did here: https://github.com/mac-s-g/react-json-view/issues/121#issuecomment-670431408

I wouldn't say this lib is not recommended for Docusaurus, but as any lib without proper SSR support, we have to work around the lack of SSR support.

**Comment by arifszn** [comment]
@slorber I tried using [react-json-inspector](https://github.com/Lapple/react-json-inspector) as an alternative but same error occurred. Then switched to [react-json-tree](https://github.com/reduxjs/redux-devtools/tree/master/packages/react-json-tree) and it is running perfectly without any hack. I would recommend [react-json-tree](https://github.com/reduxjs/redux-devtools/tree/master/packages/react-json-tree) for Docusaurus.

Running Example is here: https://arifszn.github.io/reddit-image-fetcher/docs

**Comment by slorber** [comment]
This is not really a "hack", it's just rendering it only on the client, which is a technique you should have in your bag as a React developer. I mean, you shouldn't dismiss a lib just for lack of SSR support, particularly for things like json trees for which SEO does not matter much.

Here's also a working version of this lib in Docusaurus: https://v2.docusaurus.io/__docusaurus/debug/

I agree that react-json-tree looks nice and is probably easier to integrate with Docusaurus (or Gatsby or NextJS), but that should not be the only thing to consider when making a choice.

**Comment by correiamp** [comment]
@thomasjm and @justinmchase, first of all, thank you for your amazing work!
Just wondering, relative to this https://github.com/mac-s-g/react-json-view/pull/298, do you guys have an ETA to go live?

**Comment by thomasjm** [comment]
@correiamp I think it just needs some review. If people could try it out and chime in that it works and doesn't mess anything up visually, hopefully we can get it merged. (Last I checked this project was only semi-maintained.)

You can stick the following in your `package.json`: 

```json
"react-json-view": "git+https://github.com/thomasjm/react-json-view.git#831b37f8e09b2d28ceb76fef024f1c221f1db0f7"
```

**Comment by justinmchase** [comment]
@correiamp I'm not a developer on this project but I would recommend everyone go to the PR (#298) and vote there because the developers appear to be simply unaware of the PR completely. If they were to see enough votes they may be inclined to merge it.

**Comment by correiamp** [comment]
@thomasjm and @justinmchase  sorry the late reply.
I've tested as you suggested and worked smoothly :) 

Going to add this feedback to the PR

**Comment by vongohren** [comment]
> @correiamp I think it just needs some review. If people could try it out and chime in that it works and doesn't mess anything up visually, hopefully we can get it merged. (Last I checked this project was only semi-maintained.)
> 
> You can stick the following in your `package.json`:
> 
> ```json
> "react-json-view": "git+https://github.com/thomasjm/react-json-view.git#e9baddc761536929f436e93baa5cebc5be519417"
> ```

@thomasjm Im using your package version on SSR side. But when using it as the simples demo example showcase, I get an empty object back, and it fails my render. I wonder why as I cannot find anything in the docs pointing to renderJson should return an empty object.

**Comment by thomasjm** [comment]
@vongohren I'm not sure, but there's been a bunch of commits on `master` branch since my PR was merged--I'd recommend trying the latest first.

**Comment by vongohren** [comment]
Nothing helped, so skipping this lib

**Comment by jjoker0110** [comment]
I'm also getting a similar error, it works right after restarting the develop local server but any time after it fails with this message:

```
Failed to Server Render (SSR)
Error message:
document is not defined

File:
node_modules/react-json-view/dist/main.js:1:81149
```

I'm using this with Gatsby.js

**Comment by marlonguimaraes** [comment]
I got around using this:

```js
export const BrowserOnlyReactJson = (props) => {
  if (typeof window === 'undefined') {
    return null;
  }
  const ReactJson = require('react-json-view').default;
  return <ReactJson {...props} />;
};
```

**Comment by marlonguimaraes** [comment]
If you're using **Next.js**, you can use [Dynamic Imports](https://nextjs.org/docs/advanced-features/dynamic-import):

```typescript
import dynamic from 'next/dynamic';

const BrowserReactJsonView = dynamic(() => import('react-json-view'), {
  ssr: false,
});

function Page() {
  return (
    <div>
      <BrowserReactJsonView src={client} />
    </div>
  );
  );
}
```

**Comment by Himself65** [comment]
see https://github.com/TexteaInc/json-viewer

**Comment by slorber** [comment]
> > ```js
> > export const BrowserOnlyReactJson = (props) => {
> >   if (typeof window === 'undefined') {
> >     return null;
> >   }
> >   const ReactJson = require('react-json-view').default;
> >   return <ReactJson {...props} />;
> > };
> > ```
> 
> This worked for me using Gatsby.js, thank you @marlonguimaraes !

This can cause hydration issues because the JSX rendered on the server/client is not exactly the same. React 18 will likely emit an hydration error BTW.

**Comment by cube-dan** [comment]
Thanks for the hot tip @Himself65! Works perfect with [Next.js SSR](https://github.com/TexteaInc/json-viewer#features).

**Comment by janwirth** [comment]
I like to wrap it in this component:
```ts
import { useEffect, useState } from "react";

interface Props {
  fallback?: JSX.Element; // JSX.Element
}

export const NoSSR = ({
  children,
  fallback,
}: React.PropsWithChildren<Props>): JSX.Element => {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);

  if (!mounted) {
    return fallback || <></>;
  }

  return children as JSX.Element;
};
```

**Comment by gildembergleite** [comment]
Next.js 14.2.15 with React 18

```tsx
'use client'

import dynamic from 'next/dynamic'
const ReactJson = dynamic(() => import('react-json-view'), { ssr: false })

export function HighlightedJSON({ data }: { data: object }) {
  return (
    <ReactJson
      src={data}
      theme="bright:inverted"
      collapsed={false}
      displayObjectSize={false}
      enableClipboard={false}
      displayDataTypes={false}
      groupArraysAfterLength={5}
      style={{
        padding: 10,
      }}
    />
  )
}
```
